### ISSUE TITLE
Conexp Reader/Writer

### ISSUE THREAD

**Issue by mikulatomas** [mikulatomas/convertme#9]

**Comment by RadekJanostik** [comment]
Which format you exactly mean? iThought that conexp is using burneister
cxt...

Dne st 1. 4. 2020 11:58 uživatel Tomáš Mikula <notifications@github.com>
napsal:

**Comment by tomasurbanec** [comment]
ConExp native format *.cex.

**Comment by tomasurbanec** [comment]
I have just pushed changes solving the problem with tests in <= 3.7. If no bug arises, I think we can close this issue. Maybe we can add some support for other cex file features (lattices, implications, ...) in the future - leads to metadata issue #18 ?
